prefix dcterms: <http://purl.org/dc/terms/>
prefix ns1: <http://purl.obolibrary.org/obo/>
prefix ns2: <http://semanticscience.org/resource/>
prefix ns3: <http://umc.nl/genetics/FAIR/properties/>
prefix ns4: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix wikidata_prop: <http://www.wikidata.org/prop/direct/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?ensembl_gene_id ?ncbi_gene_id ?hgvs
WHERE{
  VALUES ?ensGene {<http://rdf.ebi.ac.uk/resource/ensembl/ENSG00000181143>}
  ?variant <http://www.wikidata.org/prop/direct/P3433> ?ensGene ;
  		 dcterms:identifier ?hgvs .
  ?ensGene dcterms:identifier ?ensembl_gene_id .
             
  SERVICE <https://query.wikidata.org/bigdata/namespace/wdq/sparql> {
    ?gene wikidata_prop:P351 ?ncbi_gene_id ;
          wikidata_prop:P594 ?ensembl_gene_id .
    }
}