prefix dcterms: <http://purl.org/dc/terms/>
prefix ns1: <http://purl.obolibrary.org/obo/>
prefix ns2: <http://semanticscience.org/resource/>
prefix ns3: <http://umc.nl/genetics/FAIR/properties/>
prefix ns4: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix wikidata_prop: <http://www.wikidata.org/prop/direct/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(*) as ?count)
WHERE{
  ?variant <http://www.wikidata.org/prop/direct/P3433> <http://rdf.ebi.ac.uk/resource/ensembl/ENSG00000181143>.
  ?measurement <http://semanticscience.org/resource/SIO_000628> ?variant.
  ?measurement <http://semanticscience.org/resource/SIO_000300> ?gt
}
